import { createContext, useState, useContext, useEffect } from 'react';
import { courseTranslationsUz, courseTranslationsRu, courseTranslationsEn } from './CourseTranslations';

const translations = {
    uz: {
        "sidebar.myCourses": "Mening Kurslarim",
        "sidebar.certificates": "Sertifikatlar",
        "sidebar.groupChat": "Guruh Chat",
        "sidebar.settings": "Sozlamalar",
        "header.search": "Qidirish...",
        "header.notifications": "Bildirishnomalar",
        "header.readAll": "Barchasini o'qish",
        "header.edit": "Tahrirlash",
        "header.logout": "Chiqish",
        "settings.title": "Sozlamalar",
        "settings.profile": "Profil",
        "settings.security": "Xavfsizlik",
        "settings.notifications": "Bildirishnomalar",
        "settings.app": "Ilova",
        "settings.profileSettings": "Profil Sozlamalari",
        "settings.uploadPic": "Rasm yuklash",
        "settings.maxSize": "Maksimal hajm: 2MB (JPG, PNG)",
        "settings.fullName": "Ism Familiya",
        "settings.profession": "Kasb / Yonalish",
        "settings.about": "O'zingiz haqingizda",
        "settings.save": "Saqlash",
        "settings.securityDesc": "Parolingizni va akkaunt xavfsizligini boshqaring.",
        "settings.currentPass": "Joriy parol",
        "settings.newPass": "Yangi parol",
        "settings.updatePass": "Parolni yangilash",
        "settings.notifDesc": "Qaysi xabarlarni olishni xohlaysiz?",
        "settings.notif1": "Yangi dars qo'shilganda",
        "settings.notif2": "Uyga vazifa tekshirilganda",
        "settings.notif3": "Chatda xabar kelganda",
        "settings.notif4": "Email orqali yangiliklar",
        "settings.appSettings": "Ilova sozlamalari",
        "settings.appDesc": "Tashqi ko'rinish va til parametrlarini boshqaring.",
        "settings.selectLang": "Tilni tanlang",
        "settings.savedConfig": "Sozlamalar saqlandi!",
        "courses.title": "Mening Kurslarim",
        "courses.completed": "tugatildi",
        "courses.lessons": "dars",
        "course.1.title": "3D Max Asoslari: Noldan Pro darajasigacha",
        "course.1.instructor": "Alisher Uzoqov",
        "course.2.title": "Interyer Vizualizatsiyasi (Corona Render)",
        "course.2.instructor": "Malika Karimova",
        "course.3.title": "Eksteryer va Landshaft Dizayni",
        "course.3.instructor": "Davronbek",
        "course.4.title": "3ds Max: arxitektura kursi",
        "course.4.instructor": "Alisher Uzoqov",
        "coursePlayer.syllabus": "Kurs Mundarijasi",
        "coursePlayer.lessonsCompleted": "dars tugatildi",
        "coursePlayer.backToCourses": "Kurslarga qaytish",
        "coursePlayer.homework": "Uyga Vazifa",
        "coursePlayer.homeworkDesc": "Ishingizni pastdagi yuklash oynasiga yuboring",
        "coursePlayer.loadingVideo": "Video yuklanmoqda:",
        "coursePlayer.completed": "Tugatilgan",
        "coursePlayer.markCompleted": "Tugatdim",
        "certificates.title": "Mening Sertifikatlarim",
        "certificates.courseCert": "Kurs sertifikati",
        "certificates.issueDate": "Berilgan sana:",
        "certificates.view": "Ko'rish",
        "certificates.saveAsPdf": "PDF sifatida saqlash",
        "certificates.close": "Yopish",
        "chat.messages": "Xabarlar",
        "chat.searchPlaceholder": "Guruh yoki ism...",
        "chat.typing": "Yozishmoqda...",
        "chat.groupStatus": "24 a'zo, 5 onlayn",
        "chat.online": "Onlayn",
        "chat.today": "Bugun",
        "chat.inputPlaceholder": "Xabar yozing...",
        "chat.selectGroup": "Guruhni tanlang",
        "cert.center": "Online Ta'lim Markazi",
        "cert.id": "Sertifikat ID",
        "cert.title": "Muvaffaqiyat Sertifikati",
        "cert.thisIsTo": "Ushbu sertifikat",
        "cert.forCompleting": "quyidagi kursni to'liq yakunlagan holda taqdim etiladi",
        "cert.description": "Kurs davomida barcha modul va topshiriqlarni muvaffaqiyatli bajarib, kasbiy bilim va ko'nikmalarni o'zlashtirdi.",
        "cert.verified": "Tasdiqlangan",
        "cert.issueDate": "Berilgan Sana",
        ...courseTranslationsUz
    },
    ru: {
        "sidebar.myCourses": "Мои курсы",
        "sidebar.certificates": "Сертификаты",
        "sidebar.groupChat": "Групповой чат",
        "sidebar.settings": "Настройки",
        "header.search": "Поиск...",
        "header.notifications": "Уведомления",
        "header.readAll": "Прочитать всё",
        "header.edit": "Редактировать",
        "header.logout": "Выход",
        "settings.title": "Настройки",
        "settings.profile": "Профиль",
        "settings.security": "Безопасность",
        "settings.notifications": "Уведомления",
        "settings.app": "Приложение",
        "settings.profileSettings": "Настройки профиля",
        "settings.uploadPic": "Загрузить фото",
        "settings.maxSize": "Макс. размер: 2МБ (JPG, PNG)",
        "settings.fullName": "Имя Фамилия",
        "settings.profession": "Профессия / Направление",
        "settings.about": "О себе",
        "settings.save": "Сохранить",
        "settings.securityDesc": "Управляйте паролем и безопасностью аккаунта.",
        "settings.currentPass": "Текущий пароль",
        "settings.newPass": "Новый пароль",
        "settings.updatePass": "Обновить пароль",
        "settings.notifDesc": "Какие сообщения вы хотите получать?",
        "settings.notif1": "Когда добавлено новое занятие",
        "settings.notif2": "Когда проверено домашнее задание",
        "settings.notif3": "Когда приходит сообщение в чат",
        "settings.notif4": "Новости по Email",
        "settings.appSettings": "Настройки приложения",
        "settings.appDesc": "Управляйте параметрами внешнего вида и языка.",
        "settings.selectLang": "Выберите язык",
        "settings.savedConfig": "Настройки сохранены!",
        "courses.title": "Мои курсы",
        "courses.completed": "завершено",
        "courses.lessons": "уроков",
        "course.1.title": "Основы 3D Max: С нуля до профи",
        "course.1.instructor": "Алишер Узоков",
        "course.2.title": "Визуализация интерьера (Corona Render)",
        "course.2.instructor": "Малика Каримова",
        "course.3.title": "Экстерьер и Ландшафтный дизайн",
        "course.3.instructor": "Давронбек",
        "course.4.title": "3ds Max: Архитектурный курс",
        "course.4.instructor": "Алишер Узоков",
        "coursePlayer.syllabus": "Оглавление курса",
        "coursePlayer.lessonsCompleted": "уроков завершено",
        "coursePlayer.backToCourses": "Вернуться к курсам",
        "coursePlayer.homework": "Домашнее задание",
        "coursePlayer.homeworkDesc": "Отправьте свою работу в окно загрузки ниже",
        "coursePlayer.loadingVideo": "Загрузка видео:",
        "coursePlayer.completed": "Завершено",
        "coursePlayer.markCompleted": "Отметить завершенным",
        "certificates.title": "Мои сертификаты",
        "certificates.courseCert": "Сертификат курса",
        "certificates.issueDate": "Дата выдачи:",
        "certificates.view": "Посмотреть",
        "certificates.saveAsPdf": "Сохранить как PDF",
        "certificates.close": "Закрыть",
        "chat.messages": "Сообщения",
        "chat.searchPlaceholder": "Группа или имя...",
        "chat.typing": "Печатает...",
        "chat.groupStatus": "24 участника, 5 в сети",
        "chat.online": "В сети",
        "chat.today": "Сегодня",
        "chat.inputPlaceholder": "Напишите сообщение...",
        "chat.selectGroup": "Выберите группу",
        "cert.center": "Онлайн учебный центр",
        "cert.id": "ID Сертификата",
        "cert.title": "Сертификат успеха",
        "cert.thisIsTo": "Данный сертификат",
        "cert.forCompleting": "вручается за полное завершение следующего курса",
        "cert.description": "В ходе курса успешно выполнил все модули и задания, освоил профессиональные знания и навыки.",
        "cert.verified": "Подтверждено",
        "cert.issueDate": "Дата выдачи",
        ...courseTranslationsRu
    },
    en: {
        "sidebar.myCourses": "My Courses",
        "sidebar.certificates": "Certificates",
        "sidebar.groupChat": "Group Chat",
        "sidebar.settings": "Settings",
        "header.search": "Search...",
        "header.notifications": "Notifications",
        "header.readAll": "Read all",
        "header.edit": "Edit",
        "header.logout": "Log Out",
        "settings.title": "Settings",
        "settings.profile": "Profile",
        "settings.security": "Security",
        "settings.notifications": "Notifications",
        "settings.app": "App",
        "settings.profileSettings": "Profile Settings",
        "settings.uploadPic": "Upload picture",
        "settings.maxSize": "Max size: 2MB (JPG, PNG)",
        "settings.fullName": "Full Name",
        "settings.profession": "Profession / Direction",
        "settings.about": "About yourself",
        "settings.save": "Save",
        "settings.securityDesc": "Manage your password and account security.",
        "settings.currentPass": "Current password",
        "settings.newPass": "New password",
        "settings.updatePass": "Update password",
        "settings.notifDesc": "Which messages do you want to receive?",
        "settings.notif1": "When a new lesson is added",
        "settings.notif2": "When homework is checked",
        "settings.notif3": "When a message arrives in chat",
        "settings.notif4": "News via Email",
        "settings.appSettings": "App settings",
        "settings.appDesc": "Manage appearance and language parameters.",
        "settings.selectLang": "Select language",
        "settings.savedConfig": "Settings saved!",
        "courses.title": "My Courses",
        "courses.completed": "completed",
        "courses.lessons": "lessons",
        "course.1.title": "3D Max Basics: From Zero to Pro",
        "course.1.instructor": "Alisher Uzokov",
        "course.2.title": "Interior Visualization (Corona Render)",
        "course.2.instructor": "Malika Karimova",
        "course.3.title": "Exterior and Landscape Design",
        "course.3.instructor": "Davronbek",
        "course.4.title": "3ds Max: Architectural Course",
        "course.4.instructor": "Alisher Uzokov",
        "coursePlayer.syllabus": "Course Syllabus",
        "coursePlayer.lessonsCompleted": "lessons completed",
        "coursePlayer.backToCourses": "Back to courses",
        "coursePlayer.homework": "Homework",
        "coursePlayer.homeworkDesc": "Submit your work to the upload box below",
        "coursePlayer.loadingVideo": "Loading video:",
        "coursePlayer.completed": "Completed",
        "coursePlayer.markCompleted": "Mark as complete",
        "certificates.title": "My Certificates",
        "certificates.courseCert": "Course Certificate",
        "certificates.issueDate": "Issue date:",
        "certificates.view": "View",
        "certificates.saveAsPdf": "Save as PDF",
        "certificates.close": "Close",
        "chat.messages": "Messages",
        "chat.searchPlaceholder": "Group or name...",
        "chat.typing": "Typing...",
        "chat.groupStatus": "24 members, 5 online",
        "chat.online": "Online",
        "chat.today": "Today",
        "chat.inputPlaceholder": "Type a message...",
        "chat.selectGroup": "Select a group",
        "cert.center": "Online Education Center",
        "cert.id": "Certificate ID",
        "cert.title": "Certificate of Achievement",
        "cert.thisIsTo": "This is to certify that",
        "cert.forCompleting": "has successfully completed the following course",
        "cert.description": "Having successfully completed all modules and assignments throughout the course, mastering professional knowledge and skills.",
        "cert.verified": "Verified",
        "cert.issueDate": "Date of Issue",
        ...courseTranslationsEn
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Load language from localStorage or default to 'uz'
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('language') || 'uz';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
